package com.beans.lexer;


public enum Kind
{
    WELL,FOR,IF,THEN,ELSE,WHILE,DO, END,NOTER,TER,
    ID, NUM,DRI,
    PLUS,MINUS,TIMES,SLASH, COLON, COLEQUAL,F,
    LPAREN, NEPAREN, LEPAREN, REPAREN,RPAREN,
    EQUAL,SEMICOLON,LBRACKET,RBRACKET,
    UNTIL, INT, INPUT, OUTPUT
};